### ISSUE TITLE
Invalid hook call help?

### ISSUE THREAD

**Issue by greg-otterpeak** [Azure/react-azure-maps#127]
I'm sure this is something I'm doing wrong, but I'm stuck and am hoping you can point me in the right direction.  I'm trying to get the simple default example working and am getting the following when I navigate to the page that contains the React stuff.  Here is the code for that page:

```
import * as React from 'react';
import {
    AzureMap,
    AzureMapsProvider,
    IAzureMapOptions,
} from 'react-azure-maps';
import { AuthenticationType } from 'azure-maps-control';

const option: IAzureMapOptions = {
    authOptions: {
        authType: AuthenticationType.subscriptionKey,
        subscriptionKey: "***MY KEY***"
    },
}

export default function Assets() {
    return (
        <div style={{ height: '300px' }}>
            <AzureMapsProvider>
                <AzureMap options={option}>
                </AzureMap>
            </AzureMapsProvider>
        </div>
    );
}
```
It is being called like this:

```
import * as React from 'react';
import { Route } from 'react-router';
import Layout from './components/Layout';
import Home from './components/Home';
import Counter from './components/Counter';
import FetchData from './components/FetchData';
import CoreEditor from './components/CoreEditor';
import Assets from './components/Assets';

import './custom.css'

export default () => (
    <Layout>
        <Route exact path='/' component={Home} />
        <Route path='/counter' component={Counter} />
        <Route path='/fetch-data/:startDateIndex?' component={FetchData} />
        <Route path='/core-editor' component={CoreEditor} />
        <Route path='/assets' component={Assets} />
    </Layout>
);

```

Here is the client developer console log.  

Thanks so much for any pointers.  If I had control of it, I would know what to look for (since I've had this in my own code).  I'm NOT an expert on React and am learning as I go.  

```
log.js:24 [HMR] Waiting for update signal from WDS...
        
       Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem. 
    at g (https://localhost:44309/static/js/0.chunk.js:76028:16)
    at div
    at Assets
    at Route (https://localhost:44309/static/js/0.chunk.js:261833:29)
    at div
    at Container (https://localhost:44309/static/js/0.chunk.js:268296:25)
    at Layout (https://localhost:44309/static/js/main.chunk.js:3530:206)
    at Router (https://localhost:44309/static/js/0.chunk.js:261470:30)
    at ConnectedRouter (https://localhost:44309/static/js/0.chunk.js:173564:7)
    at ConnectedRouterWithContext (https://localhost:44309/static/js/0.chunk.js:173661:25)
    at ConnectFunction (https://localhost:44309/static/js/0.chunk.js:259678:75)
    at Provider (https://localhost:44309/static/js/0.chunk.js:259495:20)
console.<computed> @ index.js:1
overrideMethod @ react_devtools_backend.js:4026
printWarning @ react.development.js:207
error @ react.development.js:181
resolveDispatcher @ react.development.js:1590
useState @ react.development.js:1619
g @ react-azure-maps.es5.js:55
renderWithHooks @ react-dom.development.js:14977
mountIndeterminateComponent @ react-dom.development.js:17803
beginWork @ react-dom.development.js:19041
beginWork$1 @ react-dom.development.js:23932
performUnitOfWork @ react-dom.development.js:22768
workLoopSync @ react-dom.development.js:22699
renderRootSync @ react-dom.development.js:22662
performSyncWorkOnRoot @ react-dom.development.js:22285
(anonymous) @ react-dom.development.js:11319
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11268
flushSyncCallbackQueueImpl @ react-dom.development.js:11314
flushSyncCallbackQueue @ react-dom.development.js:11301
discreteUpdates$1 @ react-dom.development.js:22412
discreteUpdates @ react-dom.development.js:3756
dispatchDiscreteEvent @ react-dom.development.js:5881
index.js:1 
        
       Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem. 
    at g (https://localhost:44309/static/js/0.chunk.js:76028:16)
    at div
    at Assets
    at Route (https://localhost:44309/static/js/0.chunk.js:261833:29)
    at div
    at Container (https://localhost:44309/static/js/0.chunk.js:268296:25)
    at Layout (https://localhost:44309/static/js/main.chunk.js:3530:206)
    at Router (https://localhost:44309/static/js/0.chunk.js:261470:30)
    at ConnectedRouter (https://localhost:44309/static/js/0.chunk.js:173564:7)
    at ConnectedRouterWithContext (https://localhost:44309/static/js/0.chunk.js:173661:25)
    at ConnectFunction (https://localhost:44309/static/js/0.chunk.js:259678:75)
    at Provider (https://localhost:44309/static/js/0.chunk.js:259495:20)
console.<computed> @ index.js:1
overrideMethod @ react_devtools_backend.js:4026
printWarning @ react.development.js:207
error @ react.development.js:181
resolveDispatcher @ react.development.js:1590
useState @ react.development.js:1619
g @ react-azure-maps.es5.js:55
renderWithHooks @ react-dom.development.js:14977
mountIndeterminateComponent @ react-dom.development.js:17803
beginWork @ react-dom.development.js:19041
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
beginWork$1 @ react-dom.development.js:23956
performUnitOfWork @ react-dom.development.js:22768
workLoopSync @ react-dom.development.js:22699
renderRootSync @ react-dom.development.js:22662
performSyncWorkOnRoot @ react-dom.development.js:22285
(anonymous) @ react-dom.development.js:11319
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11268
flushSyncCallbackQueueImpl @ react-dom.development.js:11314
flushSyncCallbackQueue @ react-dom.development.js:11301
discreteUpdates$1 @ react-dom.development.js:22412
discreteUpdates @ react-dom.development.js:3756
dispatchDiscreteEvent @ react-dom.development.js:5881
react.development.js:1620 
        
       Uncaught TypeError: Cannot read properties of null (reading 'useState')
    at useState (react.development.js:1620:1)
    at g (react-azure-maps.es5.js:55:1)
    at renderWithHooks (react-dom.development.js:14977:1)
    at mountIndeterminateComponent (react-dom.development.js:17803:1)
    at beginWork (react-dom.development.js:19041:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at beginWork$1 (react-dom.development.js:23956:1)
    at performUnitOfWork (react-dom.development.js:22768:1)
    at workLoopSync (react-dom.development.js:22699:1)
    at renderRootSync (react-dom.development.js:22662:1)
    at performSyncWorkOnRoot (react-dom.development.js:22285:1)
    at react-dom.development.js:11319:1
    at unstable_runWithPriority (scheduler.development.js:468:1)
    at runWithPriority$1 (react-dom.development.js:11268:1)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11314:1)
    at flushSyncCallbackQueue (react-dom.development.js:11301:1)
    at discreteUpdates$1 (react-dom.development.js:22412:1)
    at discreteUpdates (react-dom.development.js:3756:1)
    at dispatchDiscreteEvent (react-dom.development.js:5881:1)
useState @ react.development.js:1620
g @ react-azure-maps.es5.js:55
renderWithHooks @ react-dom.development.js:14977
mountIndeterminateComponent @ react-dom.development.js:17803
beginWork @ react-dom.development.js:19041
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
beginWork$1 @ react-dom.development.js:23956
performUnitOfWork @ react-dom.development.js:22768
workLoopSync @ react-dom.development.js:22699
renderRootSync @ react-dom.development.js:22662
performSyncWorkOnRoot @ react-dom.development.js:22285
(anonymous) @ react-dom.development.js:11319
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11268
flushSyncCallbackQueueImpl @ react-dom.development.js:11314
flushSyncCallbackQueue @ react-dom.development.js:11301
discreteUpdates$1 @ react-dom.development.js:22412
discreteUpdates @ react-dom.development.js:3756
dispatchDiscreteEvent @ react-dom.development.js:5881
index.js:1 
        
       The above error occurred in the <g> component:

    at g (https://localhost:44309/static/js/0.chunk.js:76028:16)
    at div
    at Assets
    at Route (https://localhost:44309/static/js/0.chunk.js:261833:29)
    at div
    at Container (https://localhost:44309/static/js/0.chunk.js:268296:25)
    at Layout (https://localhost:44309/static/js/main.chunk.js:3530:206)
    at Router (https://localhost:44309/static/js/0.chunk.js:261470:30)
    at ConnectedRouter (https://localhost:44309/static/js/0.chunk.js:173564:7)
    at ConnectedRouterWithContext (https://localhost:44309/static/js/0.chunk.js:173661:25)
    at ConnectFunction (https://localhost:44309/static/js/0.chunk.js:259678:75)
    at Provider (https://localhost:44309/static/js/0.chunk.js:259495:20)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
console.<computed> @ index.js:1
overrideMethod @ react_devtools_backend.js:4026
logCapturedError @ react-dom.development.js:20077
update.callback @ react-dom.development.js:20110
callCallback @ react-dom.development.js:12310
commitUpdateQueue @ react-dom.development.js:12331
commitLifeCycles @ react-dom.development.js:20728
commitLayoutEffects @ react-dom.development.js:23418
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
commitRootImpl @ react-dom.development.js:23143
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11268
commitRoot @ react-dom.development.js:22982
performSyncWorkOnRoot @ react-dom.development.js:22321
(anonymous) @ react-dom.development.js:11319
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11268
flushSyncCallbackQueueImpl @ react-dom.development.js:11314
flushSyncCallbackQueue @ react-dom.development.js:11301
discreteUpdates$1 @ react-dom.development.js:22412
discreteUpdates @ react-dom.development.js:3756
dispatchDiscreteEvent @ react-dom.development.js:5881
react.development.js:1620 
        
       Uncaught TypeError: Cannot read properties of null (reading 'useState')
    at useState (react.development.js:1620:1)
    at g (react-azure-maps.es5.js:55:1)
    at renderWithHooks (react-dom.development.js:14977:1)
    at mountIndeterminateComponent (react-dom.development.js:17803:1)
    at beginWork (react-dom.development.js:19041:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at beginWork$1 (react-dom.development.js:23956:1)
    at performUnitOfWork (react-dom.development.js:22768:1)
    at workLoopSync (react-dom.development.js:22699:1)
    at renderRootSync (react-dom.development.js:22662:1)
    at performSyncWorkOnRoot (react-dom.development.js:22285:1)
    at react-dom.development.js:11319:1
    at unstable_runWithPriority (scheduler.development.js:468:1)
    at runWithPriority$1 (react-dom.development.js:11268:1)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11314:1)
    at flushSyncCallbackQueue (react-dom.development.js:11301:1)
    at discreteUpdates$1 (react-dom.development.js:22412:1)
    at discreteUpdates (react-dom.development.js:3756:1)
    at dispatchDiscreteEvent (react-dom.development.js:5881:1)
useState @ react.development.js:1620
g @ react-azure-maps.es5.js:55
renderWithHooks @ react-dom.development.js:14977
mountIndeterminateComponent @ react-dom.development.js:17803
beginWork @ react-dom.development.js:19041
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
beginWork$1 @ react-dom.development.js:23956
performUnitOfWork @ react-dom.development.js:22768
workLoopSync @ react-dom.development.js:22699
renderRootSync @ react-dom.development.js:22662
performSyncWorkOnRoot @ react-dom.development.js:22285
(anonymous) @ react-dom.development.js:11319
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11268
flushSyncCallbackQueueImpl @ react-dom.development.js:11314
flushSyncCallbackQueue @ react-dom.development.js:11301
discreteUpdates$1 @ react-dom.development.js:22412
discreteUpdates @ react-dom.development.js:3756
dispatchDiscreteEvent @ react-dom.development.js:5881
```

**Comment by greg-otterpeak** [comment]
More information:  

* I have other components that do useState stuff and those work.
* I do not have multiple versions of React.
* I have tried to execute the example exactly like the project's defaultmap example and it still fails the same way.  

Here is my package.json just in case that is something:

```
{
  "name": "gdtafapp",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@emotion/react": "^11.9.0",
    "@emotion/styled": "^11.8.1",
    "@mui/material": "^5.6.1",
    "@fortawesome/react-fontawesome": "^0.1.18",
    "@fortawesome/free-solid-svg-icons": "^6.1.1",
    "bootstrap": "^4.3.1",
    "connected-react-router": "6.5.2",
    "gojs": "^2.1.48",
    "gojs-react": "^1.1.0",
    "history": "4.10.1",
    "jquery": "^3.5.1",
    "merge": "1.2.1",
    "popper.js": "^1.16.0",
    "react": "^17.0.0",
    "react-dom": "^17.0.0",
    "react-redux": "7.1.1",
    "react-router": "5.1.2",
    "react-router-dom": "5.1.2",
    "react-scripts": "^3.4.4",
    "react-draggable": "4.4.5",
    "reactstrap": "9.0.2",
    "redux": "4.0.4",
    "redux-thunk": "2.3.0",
    "svgo": "1.3.0",
    "react-azure-maps": "^0.4.3"
  },
  "devDependencies": {
    "@types/history": "4.7.3",
    "@types/jest": "24.0.19",
    "@types/node": "12.11.6",
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "@types/react-redux": "7.1.5",
    "@types/react-router": "5.1.2",
    "@types/react-router-dom": "5.1.0",
    "@types/reactstrap": "8.7.2",
    "@typescript-eslint/parser": "^2.5.0",
    "cross-env": "6.0.3",
    "eslint": "^6.5.1",
    "eslint-plugin-flowtype": "^3.13.0",
    "eslint-plugin-import": "2.18.2",
    "eslint-plugin-jsx-a11y": "6.2.3",
    "eslint-plugin-react": "7.16.0",
    "nan": "^2.14.1",
    "typescript": "^3.8.3"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "cross-env CI=true react-scripts test --env=jsdom",
    "eject": "react-scripts eject",
    "lint": "eslint ./src/**/*.ts ./src/**/*.tsx"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "resolutions": {
    "url-parse": ">=1.5.0",
    "lodash": ">=4.17.21"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ]
}
```

```
npm ls react
+-- @fortawesome/react-fontawesome@0.1.18
| `-- react@18.1.0 deduped
+-- gojs-react@1.1.1
| `-- react@18.1.0 deduped
+-- react-azure-maps@0.4.3
| `-- react@18.1.0 deduped
+-- react-dom@18.1.0
| `-- react@18.1.0 deduped
+-- react-draggable@4.4.5
| `-- react@18.1.0 deduped
`-- react@18.1.0
```

**Comment by greg-otterpeak** [comment]
This issue is resolved.  In true React fashion and after two days...  I had to modify the package.json to reference react@17.0.2, not 17.0.0.  This worked.  I don't think your documentation says anything about that...
